### ISSUE TITLE
Thank you so much for this extension !

### ISSUE THREAD

**Issue by AugmentedRealityCat** [AnonymousCervine/depth-image-io-for-SDWebui#1]
You should open the _Discussions_ panel for this repo so that other people like me can come and tell you how much we appreciate this extension you made for the Automatic1111 WebUI. This is much more convenient than the hack I had been using so far. Thank you so much.

In addition to showing our gratitude without cluttering the _Issues_ page, the _Discussions_ page could also be a great place to discuss best practices with your extension.

Thanks again for making and sharing this !

**Comment by ClashSAN** [comment]
@AugmentedRealityCat it would be nice if you are able to share anything you've made also. Do you have a working commit version for the webui for this? We can add this info here - https://github.com/ClashSAN/sd-webui-extension-records

Here was most of the discussion originally - https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5683

**Comment by AnonymousCervine** [comment]
@AugmentedRealityCat 

Discussions are now open, for what it's worth.

@ClashSAN

I can add that info there if desired (probably ~~tomorrow or the day after~~ Monday (**Edit:** Delayed because testing revealed the newer style of the 'hires fix' option breaks things? I suppose I might list it in the meantime but referencing an old webui commit, but I'll see if I can't fix things first)—I do want to sit down and test things on an up-to-date webui commit first, and all)

**Comment by AnonymousCervine** [comment]
@ClashSAN Belatedly: A pair of working commit-hashes has been added. I'll try to remember to update it periodically as time goes on; I have to test things whenever I update the extension regardless, after all.

**Comment by AugmentedRealityCat** [comment]
> it would be nice if you are able to share anything you've made also

What did you have in mind ? You mean like test images and animation prototypes ? It would be my pleasure to share them and an honour if you were to use them as examples. 
(sorry for the late reply, my computer had hardware problems, and then I had some of my own, but I'm back for good !)
